export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const ADD_MALL_REQUEST = "ADD_MALL_REQUEST"
export const ADD_MALL_SUCCESS = "ADD_MALL_SUCCESS"
export const ADD_MALL_FAILURE = "ADD_MALL_FAILURE"

export const FETCH_MALL_REQUEST = "FETCH_MALL_REQUEST"
export const FETCH_MALL_SUCCESS = "FETCH_MALL_SUCCESS"
export const FETCH_MALL_FAILURE = "FETCH_MALL_FAILURE"

export const DELETE_MALL_REQUEST = "DELETE_MALL_REQUEST"
export const DELETE_MALL_SUCCESS = "DELETE_MALL_SUCCESS"
export const DELETE_MALL_FAILURE = "DELETE_MALL_FAILURE"