export const FETCH_REQUEST = "FETCH_REQUEST"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_FAILURE = "FETCH_FAILURE"

export const DETAIL_REQUEST = "DETAIL_REQUEST"
export const DETAIL_SUCCESS = "DETAIL_SUCCESS"
export const DETAIL_FAILURE = "DETAIL_FAILURE"