export const DELETE_USER_INFO = "DELETE_USER_INFO";
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";

export const ADD_USER_RESULT = "ADD_USER_RESULT";
export const EDIT_USER_RESULT = "EDIT_USER_RESULT";
export const DELETE_USER_RESULT = "DELETE_USER_RESULT";
export const DELETE_SINGLE_RESULT = "DELETE_SINGLE_RESULT";
export const DELETE_USER_RESULT_FROM_USER_INFO =
  "DELETE_USER_RESULT_FROM_USER_INFO";

export const REGISTER_USER_RESULT_FROM_NEW_USER =
  "REGISTER_USER_RESULT_FROM_NEW_USER";
